# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 642)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(340, 0, 791, 641))
        self.graphicsView.setObjectName("graphicsView")
        self.funcs_box = QtWidgets.QComboBox(self.centralwidget)
        self.funcs_box.setGeometry(QtCore.QRect(10, 20, 311, 31))
        self.funcs_box.setObjectName("funcs_box")
        self.funcs_box.addItem("")
        self.funcs_box.addItem("")
        self.funcs_box.addItem("")
        self.funcs_box.addItem("")
        self.x_start = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.x_start.setGeometry(QtCore.QRect(20, 110, 71, 41))
        self.x_start.setMinimum(-500.0)
        self.x_start.setMaximum(500.0)
        self.x_start.setObjectName("x_start")
        self.x_end = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.x_end.setGeometry(QtCore.QRect(110, 110, 71, 41))
        self.x_end.setMinimum(-500.0)
        self.x_end.setMaximum(500.0)
        self.x_end.setObjectName("x_end")
        self.x_step = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.x_step.setGeometry(QtCore.QRect(210, 110, 71, 41))
        self.x_step.setMinimum(-500.0)
        self.x_step.setMaximum(500.0)
        self.x_step.setObjectName("x_step")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 70, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 170, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.z_end = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.z_end.setGeometry(QtCore.QRect(110, 210, 71, 41))
        self.z_end.setMinimum(-500.0)
        self.z_end.setMaximum(500.0)
        self.z_end.setObjectName("z_end")
        self.z_start = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.z_start.setGeometry(QtCore.QRect(20, 210, 71, 41))
        self.z_start.setMinimum(-500.0)
        self.z_start.setMaximum(500.0)
        self.z_start.setObjectName("z_start")
        self.z_step = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.z_step.setGeometry(QtCore.QRect(210, 210, 71, 41))
        self.z_step.setMinimum(-500.0)
        self.z_step.setMaximum(500.0)
        self.z_step.setObjectName("z_step")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 170, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 81, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 300, 71, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 346, 41, 20))
        self.label_8.setObjectName("label_8")
        self.x_rotate = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.x_rotate.setGeometry(QtCore.QRect(20, 380, 71, 41))
        self.x_rotate.setMinimum(-500.0)
        self.x_rotate.setMaximum(500.0)
        self.x_rotate.setObjectName("x_rotate")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(140, 345, 41, 21))
        self.label_9.setObjectName("label_9")
        self.y_rotate = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.y_rotate.setGeometry(QtCore.QRect(110, 380, 71, 41))
        self.y_rotate.setMinimum(-500.0)
        self.y_rotate.setMaximum(500.0)
        self.y_rotate.setObjectName("y_rotate")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(230, 345, 41, 21))
        self.label_10.setObjectName("label_10")
        self.z_rotate = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.z_rotate.setGeometry(QtCore.QRect(210, 380, 71, 41))
        self.z_rotate.setMinimum(-500.0)
        self.z_rotate.setMaximum(500.0)
        self.z_rotate.setObjectName("z_rotate")
        self.show_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_btn.setGeometry(QtCore.QRect(10, 480, 321, 41))
        self.show_btn.setObjectName("show_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.funcs_box.setItemText(0, _translate("MainWindow", "cos(x) * sin(z)"))
        self.funcs_box.setItemText(1, _translate("MainWindow", "cos(x) + sin(z)"))
        self.funcs_box.setItemText(2, _translate("MainWindow", "sin(x * z)"))
        self.funcs_box.setItemText(3, _translate("MainWindow", "x + z"))
        self.label.setText(_translate("MainWindow", "X start"))
        self.label_2.setText(_translate("MainWindow", "X end"))
        self.label_3.setText(_translate("MainWindow", "Step"))
        self.label_4.setText(_translate("MainWindow", "Step"))
        self.label_5.setText(_translate("MainWindow", "Z end"))
        self.label_6.setText(_translate("MainWindow", "Z start"))
        self.label_7.setText(_translate("MainWindow", "Rotate"))
        self.label_8.setText(_translate("MainWindow", "X"))
        self.label_9.setText(_translate("MainWindow", "Y"))
        self.label_10.setText(_translate("MainWindow", "Z"))
        self.show_btn.setText(_translate("MainWindow", "Show"))
