# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab3.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 868)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1011, 501))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 530, 131, 21))
        self.label.setObjectName("label")
        self.x_start = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.x_start.setGeometry(QtCore.QRect(50, 560, 90, 22))
        self.x_start.setMinimum(-1000.0)
        self.x_start.setMaximum(2000.0)
        self.x_start.setObjectName("x_start")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 563, 21, 16))
        self.label_2.setObjectName("label_2")
        self.y_start = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.y_start.setGeometry(QtCore.QRect(180, 560, 90, 22))
        self.y_start.setMinimum(-1000.0)
        self.y_start.setMaximum(2000.0)
        self.y_start.setObjectName("y_start")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 563, 21, 16))
        self.label_3.setObjectName("label_3")
        self.y_end = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.y_end.setGeometry(QtCore.QRect(180, 637, 90, 22))
        self.y_end.setMinimum(-1000.0)
        self.y_end.setMaximum(2000.0)
        self.y_end.setObjectName("y_end")
        self.x_end = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.x_end.setGeometry(QtCore.QRect(50, 637, 90, 22))
        self.x_end.setMinimum(-1000.0)
        self.x_end.setMaximum(2000.0)
        self.x_end.setObjectName("x_end")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 640, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 602, 131, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 640, 21, 16))
        self.label_6.setObjectName("label_6")
        self.brezenhem_float_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.brezenhem_float_radio.setGeometry(QtCore.QRect(520, 590, 191, 20))
        self.brezenhem_float_radio.setObjectName("brezenhem_float_radio")
        self.brezenhem_int_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.brezenhem_int_radio.setGeometry(QtCore.QRect(520, 620, 181, 20))
        self.brezenhem_int_radio.setObjectName("brezenhem_int_radio")
        self.brezenhem_smoothing_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.brezenhem_smoothing_radio.setGeometry(QtCore.QRect(520, 650, 231, 20))
        self.brezenhem_smoothing_radio.setObjectName("brezenhem_smoothing_radio")
        self.wu_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.wu_radio.setGeometry(QtCore.QRect(520, 680, 61, 20))
        self.wu_radio.setObjectName("wu_radio")
        self.library_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.library_radio.setGeometry(QtCore.QRect(520, 710, 161, 20))
        self.library_radio.setObjectName("library_radio")
        self.build_line = QtWidgets.QPushButton(self.centralwidget)
        self.build_line.setGeometry(QtCore.QRect(90, 690, 111, 41))
        self.build_line.setObjectName("build_line")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(770, 530, 91, 21))
        self.label_7.setObjectName("label_7")
        self.make_line_black = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_black.setGeometry(QtCore.QRect(770, 560, 93, 28))
        self.make_line_black.setObjectName("make_line_black")
        self.make_line_blue = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_blue.setGeometry(QtCore.QRect(770, 600, 93, 28))
        self.make_line_blue.setObjectName("make_line_blue")
        self.make_line_red = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_red.setGeometry(QtCore.QRect(770, 640, 93, 28))
        self.make_line_red.setObjectName("make_line_red")
        self.make_line_green = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_green.setGeometry(QtCore.QRect(770, 680, 93, 28))
        self.make_line_green.setObjectName("make_line_green")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(880, 530, 91, 21))
        self.label_8.setObjectName("label_8")
        self.make_bg_white = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_white.setGeometry(QtCore.QRect(880, 560, 93, 28))
        self.make_bg_white.setObjectName("make_bg_white")
        self.make_bg_green = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_green.setGeometry(QtCore.QRect(880, 680, 93, 28))
        self.make_bg_green.setObjectName("make_bg_green")
        self.make_bg_blue = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_blue.setGeometry(QtCore.QRect(880, 600, 93, 28))
        self.make_bg_blue.setObjectName("make_bg_blue")
        self.make_bg_red = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_red.setGeometry(QtCore.QRect(880, 640, 93, 28))
        self.make_bg_red.setObjectName("make_bg_red")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 530, 181, 21))
        self.label_9.setObjectName("label_9")
        self.length = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.length.setGeometry(QtCore.QRect(310, 590, 90, 22))
        self.length.setMinimum(-1000.0)
        self.length.setMaximum(1000.0)
        self.length.setObjectName("length")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 560, 21, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.build_sun = QtWidgets.QPushButton(self.centralwidget)
        self.build_sun.setGeometry(QtCore.QRect(340, 650, 111, 41))
        self.build_sun.setObjectName("build_sun")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(520, 530, 181, 21))
        self.label_11.setObjectName("label_11")
        self.make_line_white = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_white.setGeometry(QtCore.QRect(770, 720, 93, 28))
        self.make_line_white.setObjectName("make_line_white")
        self.make_bg_black = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_black.setGeometry(QtCore.QRect(880, 720, 93, 28))
        self.make_bg_black.setObjectName("make_bg_black")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(310, 560, 51, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(410, 560, 41, 21))
        self.label_13.setObjectName("label_13")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(810, 780, 161, 51))
        self.clear_btn.setObjectName("clear_btn")
        self.cda_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.cda_radio.setGeometry(QtCore.QRect(520, 560, 191, 20))
        self.cda_radio.setObjectName("cda_radio")
        self.step = QtWidgets.QSpinBox(self.centralwidget)
        self.step.setGeometry(QtCore.QRect(410, 590, 90, 22))
        self.step.setMinimum(1)
        self.step.setMaximum(180)
        self.step.setObjectName("step")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(30, 760, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 780, 55, 16))
        self.label_15.setObjectName("label_15")
        self.brush_thickness = QtWidgets.QSpinBox(self.centralwidget)
        self.brush_thickness.setGeometry(QtCore.QRect(110, 770, 90, 22))
        self.brush_thickness.setMinimum(1)
        self.brush_thickness.setMaximum(20)
        self.brush_thickness.setObjectName("brush_thickness")
        self.change_thickness = QtWidgets.QPushButton(self.centralwidget)
        self.change_thickness.setGeometry(QtCore.QRect(210, 767, 93, 28))
        self.change_thickness.setObjectName("change_thickness")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Начало отрезка"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.label_4.setText(_translate("MainWindow", "Y"))
        self.label_5.setText(_translate("MainWindow", "Конец отрезка"))
        self.label_6.setText(_translate("MainWindow", "X"))
        self.brezenhem_float_radio.setText(_translate("MainWindow", "Брезенхем (действ.)"))
        self.brezenhem_int_radio.setText(_translate("MainWindow", "Брезенхем (целые)"))
        self.brezenhem_smoothing_radio.setText(_translate("MainWindow", "Брезенхем (сглаживание)"))
        self.wu_radio.setText(_translate("MainWindow", "Ву"))
        self.library_radio.setText(_translate("MainWindow", "Библиотечный"))
        self.build_line.setText(_translate("MainWindow", "Построить"))
        self.label_7.setText(_translate("MainWindow", "Цвет линии"))
        self.make_line_black.setText(_translate("MainWindow", "Чёрный"))
        self.make_line_blue.setText(_translate("MainWindow", "Синий"))
        self.make_line_red.setText(_translate("MainWindow", "Красный"))
        self.make_line_green.setText(_translate("MainWindow", "Зеленый"))
        self.label_8.setText(_translate("MainWindow", "Цвет фона"))
        self.make_bg_white.setText(_translate("MainWindow", "Белый"))
        self.make_bg_green.setText(_translate("MainWindow", "Зеленый"))
        self.make_bg_blue.setText(_translate("MainWindow", "Синий"))
        self.make_bg_red.setText(_translate("MainWindow", "Красный"))
        self.label_9.setText(_translate("MainWindow", "Линии по окружности"))
        self.build_sun.setText(_translate("MainWindow", "Построить"))
        self.label_11.setText(_translate("MainWindow", "Способы"))
        self.make_line_white.setText(_translate("MainWindow", "Белый"))
        self.make_bg_black.setText(_translate("MainWindow", "Чёрный"))
        self.label_12.setText(_translate("MainWindow", "Длина"))
        self.label_13.setText(_translate("MainWindow", "Шаг"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.cda_radio.setText(_translate("MainWindow", "ЦДА"))
        self.label_14.setText(_translate("MainWindow", "Толщина"))
        self.label_15.setText(_translate("MainWindow", "кисти"))
        self.change_thickness.setText(_translate("MainWindow", "Изменить"))
