# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab5.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 735)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(250, 0, 711, 521))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 540, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 540, 16, 16))
        self.label_2.setObjectName("label_2")
        self.x_point_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.x_point_box.setGeometry(QtCore.QRect(20, 560, 62, 22))
        self.x_point_box.setMaximum(1000.0)
        self.x_point_box.setObjectName("x_point_box")
        self.y_point_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.y_point_box.setGeometry(QtCore.QRect(100, 560, 62, 22))
        self.y_point_box.setMaximum(1000.0)
        self.y_point_box.setObjectName("y_point_box")
        self.add_point_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_point_btn.setGeometry(QtCore.QRect(20, 590, 141, 28))
        self.add_point_btn.setObjectName("add_point_btn")
        self.delay = QtWidgets.QCheckBox(self.centralwidget)
        self.delay.setGeometry(QtCore.QRect(260, 540, 101, 20))
        self.delay.setObjectName("delay")
        self.fill_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fill_btn.setGeometry(QtCore.QRect(260, 600, 91, 28))
        self.fill_btn.setObjectName("fill_btn")
        self.end_btn = QtWidgets.QPushButton(self.centralwidget)
        self.end_btn.setGeometry(QtCore.QRect(260, 570, 91, 28))
        self.end_btn.setObjectName("end_btn")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(260, 630, 91, 28))
        self.clear_btn.setObjectName("clear_btn")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(420, 530, 91, 21))
        self.label_7.setObjectName("label_7")
        self.make_line_black = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_black.setGeometry(QtCore.QRect(420, 560, 93, 28))
        self.make_line_black.setObjectName("make_line_black")
        self.make_line_red = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_red.setGeometry(QtCore.QRect(420, 620, 93, 28))
        self.make_line_red.setObjectName("make_line_red")
        self.make_line_blue = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_blue.setGeometry(QtCore.QRect(420, 590, 93, 28))
        self.make_line_blue.setObjectName("make_line_blue")
        self.make_bg_white = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_white.setGeometry(QtCore.QRect(530, 560, 93, 28))
        self.make_bg_white.setObjectName("make_bg_white")
        self.make_bg_blue = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_blue.setGeometry(QtCore.QRect(530, 590, 93, 28))
        self.make_bg_blue.setObjectName("make_bg_blue")
        self.make_line_green = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_green.setGeometry(QtCore.QRect(420, 650, 93, 28))
        self.make_line_green.setObjectName("make_line_green")
        self.make_line_white = QtWidgets.QPushButton(self.centralwidget)
        self.make_line_white.setGeometry(QtCore.QRect(420, 680, 93, 28))
        self.make_line_white.setObjectName("make_line_white")
        self.make_bg_black = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_black.setGeometry(QtCore.QRect(530, 680, 93, 28))
        self.make_bg_black.setObjectName("make_bg_black")
        self.make_bg_red = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_red.setGeometry(QtCore.QRect(530, 620, 93, 28))
        self.make_bg_red.setObjectName("make_bg_red")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 530, 91, 21))
        self.label_8.setObjectName("label_8")
        self.make_bg_green = QtWidgets.QPushButton(self.centralwidget)
        self.make_bg_green.setGeometry(QtCore.QRect(530, 650, 93, 28))
        self.make_bg_green.setObjectName("make_bg_green")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 51, 20))
        self.label_3.setObjectName("label_3")
        self.points_table = QtWidgets.QTextEdit(self.centralwidget)
        self.points_table.setGeometry(QtCore.QRect(10, 40, 191, 481))
        self.points_table.setObjectName("points_table")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "X"))
        self.label_2.setText(_translate("MainWindow", "Y"))
        self.add_point_btn.setText(_translate("MainWindow", "Добавить точку"))
        self.delay.setText(_translate("MainWindow", "Задержка"))
        self.fill_btn.setText(_translate("MainWindow", "Закрасить"))
        self.end_btn.setText(_translate("MainWindow", "Замкнуть"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.label_7.setText(_translate("MainWindow", "Цвет линии"))
        self.make_line_black.setText(_translate("MainWindow", "Чёрный"))
        self.make_line_red.setText(_translate("MainWindow", "Красный"))
        self.make_line_blue.setText(_translate("MainWindow", "Синий"))
        self.make_bg_white.setText(_translate("MainWindow", "Белый"))
        self.make_bg_blue.setText(_translate("MainWindow", "Синий"))
        self.make_line_green.setText(_translate("MainWindow", "Зеленый"))
        self.make_line_white.setText(_translate("MainWindow", "Белый"))
        self.make_bg_black.setText(_translate("MainWindow", "Чёрный"))
        self.make_bg_red.setText(_translate("MainWindow", "Красный"))
        self.label_8.setText(_translate("MainWindow", "Цвет фона"))
        self.make_bg_green.setText(_translate("MainWindow", "Зеленый"))
        self.label_3.setText(_translate("MainWindow", "Точки"))
