# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 731, 571))
        self.graphicsView.setObjectName("graphicsView")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(740, 70, 281, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 0, 31, 61))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.xFrom = QtWidgets.QSpinBox(self.centralwidget)
        self.xFrom.setGeometry(QtCore.QRect(790, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.xFrom.setFont(font)
        self.xFrom.setMinimum(-100)
        self.xFrom.setMaximum(100)
        self.xFrom.setProperty("value", -5)
        self.xFrom.setObjectName("xFrom")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(790, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(870, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.xTo = QtWidgets.QSpinBox(self.centralwidget)
        self.xTo.setGeometry(QtCore.QRect(870, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.xTo.setFont(font)
        self.xTo.setMinimum(-100)
        self.xTo.setProperty("value", 5)
        self.xTo.setObjectName("xTo")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(950, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(740, 160, 281, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(790, 90, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.zFrom = QtWidgets.QSpinBox(self.centralwidget)
        self.zFrom.setGeometry(QtCore.QRect(790, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.zFrom.setFont(font)
        self.zFrom.setMinimum(-100)
        self.zFrom.setProperty("value", -5)
        self.zFrom.setObjectName("zFrom")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(870, 90, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(950, 90, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(740, 90, 31, 61))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.zTo = QtWidgets.QSpinBox(self.centralwidget)
        self.zTo.setGeometry(QtCore.QRect(870, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.zTo.setFont(font)
        self.zTo.setMinimum(-100)
        self.zTo.setProperty("value", 5)
        self.zTo.setObjectName("zTo")
        self.xStep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xStep.setGeometry(QtCore.QRect(950, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.xStep.setFont(font)
        self.xStep.setMinimum(-100.0)
        self.xStep.setProperty("value", 0.1)
        self.xStep.setObjectName("xStep")
        self.zStep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zStep.setGeometry(QtCore.QRect(950, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.zStep.setFont(font)
        self.zStep.setMinimum(-100.0)
        self.zStep.setProperty("value", 0.1)
        self.zStep.setObjectName("zStep")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(740, 180, 191, 61))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.rotateX = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rotateX.setGeometry(QtCore.QRect(930, 180, 91, 61))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.rotateX.setFont(font)
        self.rotateX.setMinimum(-100.0)
        self.rotateX.setObjectName("rotateX")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(740, 240, 281, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.rotateY = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rotateY.setGeometry(QtCore.QRect(930, 260, 91, 61))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.rotateY.setFont(font)
        self.rotateY.setMinimum(-100.0)
        self.rotateY.setObjectName("rotateY")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(740, 260, 191, 61))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(740, 320, 281, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.rotateZ = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rotateZ.setGeometry(QtCore.QRect(930, 340, 91, 61))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.rotateZ.setFont(font)
        self.rotateZ.setMinimum(-100.0)
        self.rotateZ.setObjectName("rotateZ")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(740, 340, 191, 61))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.functions = QtWidgets.QComboBox(self.centralwidget)
        self.functions.setGeometry(QtCore.QRect(740, 460, 281, 41))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(15)
        self.functions.setFont(font)
        self.functions.setObjectName("functions")
        self.functions.addItem("")
        self.functions.addItem("")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(740, 400, 281, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(740, 420, 281, 41))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.displayButton = QtWidgets.QPushButton(self.centralwidget)
        self.displayButton.setGeometry(QtCore.QRect(740, 520, 281, 51))
        font = QtGui.QFont()
        font.setFamily("asinastra")
        font.setPointSize(20)
        self.displayButton.setFont(font)
        self.displayButton.setObjectName("displayButton")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(740, 500, 281, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "X:"))
        self.label_2.setText(_translate("MainWindow", "From:"))
        self.label_3.setText(_translate("MainWindow", "To:"))
        self.label_4.setText(_translate("MainWindow", "Step:"))
        self.label_5.setText(_translate("MainWindow", "From:"))
        self.label_6.setText(_translate("MainWindow", "To:"))
        self.label_7.setText(_translate("MainWindow", "Step:"))
        self.label_8.setText(_translate("MainWindow", "Z:"))
        self.label_9.setText(_translate("MainWindow", "Rotate x:"))
        self.label_10.setText(_translate("MainWindow", "Rotate y:"))
        self.label_11.setText(_translate("MainWindow", "Rotate z:"))
        self.functions.setItemText(0, _translate("MainWindow", "sin(x) - cos(z) * exp(x)"))
        self.functions.setItemText(1, _translate("MainWindow", "sin(x) * cos(z)"))
        self.label_12.setText(_translate("MainWindow", "Need function:"))
        self.displayButton.setText(_translate("MainWindow", "Display"))
